version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mop_gen
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio-data:/data
    command: ["server", "/data"]
  cognee-rag-api:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./cognee-rag-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - minio

volumes:
  postgres-data:
  minio-data:
  node_modules: